// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuknnfbsfhuiaqdcpmgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1a25uZmJzZmh1aWFxZGNwbWdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NjMyMTMsImV4cCI6MjA3MzQzOTIxM30.pmJjZPsVYBogB6yWQmXx_qGx_Rh74xCWILMdkCVuFqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});